### ISSUE TITLE
Mentor communication info not displayed on saving it

### ISSUE THREAD

**Issue by maskaravivek** [sagesharp/outreachy-django-wagtail#108]
Hello, 

I signed up as a mentor on the outreachy website and saved my communication username in the form, but that information is not displayed in my application.

Form:
<img width="881" alt="screen shot 2018-02-07 at 12 03 21 am" src="https://user-images.githubusercontent.com/3069373/35877058-43460eba-0b9a-11e8-9c3b-3b4d1c55717c.png">

Displayed info:
<img width="818" alt="screen shot 2018-02-07 at 12 05 45 am" src="https://user-images.githubusercontent.com/3069373/35877073-4e4936e8-0b9a-11e8-9d76-3aeefb923063.png">

**Comment by jameysharp** [comment]
Thanks for pointing this out! The fix won't get deployed for a little while longer as we're working on a bunch of other things, but it's now fixed on master and will go live whenever we get those other things up.
