### ISSUE TITLE
Add error monitoring and reporting

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#11]
Organizers should get an email on server errors and crashes, perhaps using [sentry.io](sentry.io)

**Comment by sagesharp** [comment]
Waiting on a response from Sentry.

**Comment by jameysharp** [comment]
Sentry integration has been deployed to the test site but not to the live site. It's backed up behind the piles of other changed we've been working on, but should just work once the current backlog is deployed to production.

Fixed in 933da2f1b4898d26fbead45001d1898fb3660aa2.
