### ISSUE TITLE
[CSS] Help update bootstrap

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#12]
In the past, someone only committed the minified version of the bootstrap CSS to the older Outreachy website. Thus, we only have the minified CSS version committed: https://github.com/sagesharp/outreachy-django-wagtail/blob/master/outreachyhome/static/css/bootstrap.min.css

We need to unminify it, figure out which version of bootstrap was the original version, and what changes were made against that version. Then we can make those changes to a newer version of bootstap, and commit the unminified version.

**Comment by ragesoss** [comment]
Do you know what important modifications where made?

The file says it's bootstrap 2.3.2, but it's larger than the version of bootstrap.min.css that I got from http://getbootstrap.com/2.3.2/index.html (~125k vs. 100k). However, I don't notice any differences locally when I switch in the unmodified version; I'm guessing there were modifications that affected specific content that is not it git?

Maybe an easy approach would be to switch out that bootstrap file for the unmodified version, look for any styling regressions, and then fix them via main.css and make no future modifications to the bootstrap file. (Just speculating here.)

**Comment by jameysharp** [comment]
I tackled this with pull request #21, but for reasons I don't understand GitHub didn't mark this issue closed even after that PR was merged.

**Comment by ragesoss** [comment]
@jameysharp I think the "Fixes #12" bit was only in the PR comment, but didn't end up in any of the commit messages that were merged to master, nor the [merge commit](https://github.com/sagesharp/outreachy-django-wagtail/commit/e8e7d30581dccf89bb0b7a61b858cf8059759b10). GitHub only closes the issue if it finds the closing keyword in a commit summary.

**Comment by jameysharp** [comment]
@ragesoss Thank you, that explains it! I learned something today. 😄
