### ISSUE TITLE
/eligibility/ page is not working.

### ISSUE THREAD

**Issue by heenamakhija** [sagesharp/outreachy-django-wagtail#129]
An internal server error is occurring at https://www.outreachy.org/eligibility. Please fix this. :)

**Comment by sagesharp** [comment]
@heenamakhija Please try to reload the page. We just deployed a fix for people who created an account before we started gathering additional information.

If you still see the error please provide your username or email on the Outreachy website.

**Comment by heenamakhija** [comment]
It works. Thanks!
