### ISSUE TITLE
Migrate travel page from the wiki

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#149]
This needs to be done with #8 in mind. Migrate information from this page:
https://wiki.gnome.org/Outreachy/TravelAllowance

**Comment by bkuhn** [comment]
We also need a way for whoever is handling Conservancy Accounts Payable to be able to edit that page (and likely *just* that page), as it will make reference to A/P polices and we can add it to action items for Outreachy round start-up.

**Comment by sagesharp** [comment]
@bkuhn The travel page is now in the Outreachy website repository under `home/templates/home/travel_stipend.html`. A summary of the information is displayed on both intern/alum dashboards (`home/templates/home/dashboard/intern.html`) and mentor dashboards (`home/templates/home/dashboard/mentor.html `). Anyone from Conservancy is welcome to send a pull request to update the information on those pages.
