### ISSUE TITLE
Fix typo on /apply/eligibility/

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#159]
@TheSeaOfRhun reported this bug:
> On this page is a typo:
> https://www.outreachy.org/apply/eligibility/
> The last word of the phrase "...resident living aboard ..." should read "abroad".

This is a good bug for people who are new to Django, who are somewhat familiar with running commands from the command line, and who are slightly familiar with Python.

You'll need to follow the "Setting up your development environment instructions" in the [README.md](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/README.md) file, following instructions through the end of the "Testing the local website" section. Once you do, you'll be able to navigate to your local copy of the http://127.0.0.1:8000/apply/eligibility/ form to see your local instance of the form. Any changes you make to your local code base will be automatically updated on the copy of the Outreachy website running on your local machine.

Each page on the Outreachy website is associated with one or more Django [templates](https://docs.djangoproject.com/en/2.0/topics/templates/) (unless it's a page handled by our CMS, Wagtail). A template is contains HTML and a special template language. Some Python code called a [view](https://docs.djangoproject.com/en/2.0/topics/http/views/) pulls Python objects out of the database, and renders the template, which can change contents based on those objects.

Django [figures out which view is associated with a particular URL](https://docs.djangoproject.com/en/2.0/topics/http/urls/) by looking at urls.py. In this case, the URL that is associated with "/apply/eligibility/" is found in [home/urls.py](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/urls.py#L45).

So the view you're looking for is called `eligibility_information`. If you run `git grep eligibility_information` you'll find the function is defined in [home/views.py](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/views.py#L1365). All that function does is render the template `home/eligibility.html`, passing it a Python object that is instance of the class RoundPage.

The [RoundPage](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L89) is a Django [model](https://docs.djangoproject.com/en/1.11/topics/db/models/) which contains dates associated with the current round. By storing all our important dates in one Python object, and passing that object from template to template, we update the dates in all places on all pages just by changing the value of a field in one model. This saves us a lot of time updating the website when each new round opens.

The current RoundPage is passed to the template, `home/eligibility.html`. You'll find that file in `home/eligibility/home/templates/`. Once you fix the typo and you have the Django server running, you'll be able to see you changes when you navigate to http://127.0.0.1:8000/apply/eligibility/

While you're at it, try changing other text on that page! Then try to display other dates stored in the RoundPage object, like `orgreminder` or `landingdue`. What happens if you try to display `sponsordetails`? Comment on this issue with a screenshot showing the results of your experiments, or if you get stuck.

Good luck! I'm leaving this bug here for people new to Django to fix. Don't fix this if you're already familiar with Django.

**Comment by HimanshuAwasthi95** [comment]
Hi ! I would like to contribute this issue

**Comment by HimanshuAwasthi95** [comment]
thanks
