### ISSUE TITLE
make organization cfp easier to find

### ISSUE THREAD

**Issue by JuliaLawall** [sagesharp/outreachy-django-wagtail#162]
It's hard to remember where is the link to update the information about an organization.  It seems that it is available in Notifications -> Project -> 2018 May to 2018 August round - Linux Kernel, but somehow none of this suggests that this is the way to get to the desired link.  Indeed notifications, seems oriented towards receiving information, whereas when one wants to update the page, one wants to provide information.

**Comment by sagesharp** [comment]
This should be fixed now. Please take a look.

**Comment by JuliaLawall** [comment]
It looks really good.  Thanks!
