### ISSUE TITLE
allow applicants to withdraw applications

### ISSUE THREAD

**Issue by JuliaLawall** [sagesharp/outreachy-django-wagtail#168]
Perhaps it is an issue that only arises now, because the system is new, but I have several applications where it is clear that the person was just curious about the system - one is from a coordinator and one is from a former intern.  It would be nice to be able to get rid of them, or to ask the person who created them to get rid of them.

**Comment by sagesharp** [comment]
There is a way to withdraw a final application, but no way to delete a contribution. That's documented on #114. Closing as a duplicate.
