### ISSUE TITLE
Clarify that proposals are written by applicants

### ISSUE THREAD

**Issue by marco-c** [sagesharp/outreachy-django-wagtail#169]
The text says: "Work with your mentor to provide a timeline of the work you plan to accomplish on the project and what tasks you will finish at each step.".

Unfortunately for projects that receive lots of applicants, this is really hard to do for the mentor. The mentor can help clarify things, but they can't work together with all of the applicants to provide a timeline.

**Comment by sagesharp** [comment]
@marco-c I can see where that wording would be confusing. Perhaps it should say 
> "Create a timeline of the steps you will take to implement the Internship Tasks outlined by the mentor on their project page. Try to figure out how long it will take to implement each task, and the details of what you might be working on each week. You may need to consult with your mentor to get additional details about the tasks."

If you have too many applicants pinging you about a timeline, you might want to provide a more detailed description of the internship tasks. You can add that in your project details.

However, mentors are expected to work with promising applicants to figure out a timeline. It's important that you know what your intern's schedule is, and if they (or you) need to take off any time during the internship (say for a conference or vacation). You might end up ignoring less promising applicants, but you need to work with the people you're most likely to accept as an intern to complete the timeline.

If your project has too many applicants, you should close the project to new applicants (you can do this by editing your project information).

**Comment by sagesharp** [comment]
Re-worded, and sent email to mentors and applicants who have recorded a contribution to clarify expectations.
