### ISSUE TITLE
Use relative paths in templates

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#17]
Instead of using absolute URLs in templates to point to wagtail pages like `https://www.outreachy.org/apply/eligibility/` we can use relative URLs like `/apply/eligibility/`.

Wagtail might have a template tag that we can use to reference pages by name.

**Comment by jameysharp** [comment]
I think the right Wagtail template tag for this is [slugurl](http://docs.wagtail.io/en/v1.13.1/topics/writing_templates.html#slugurl).

To point to Django pages served by custom views, the corresponding template tag is [url](https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#url).
