### ISSUE TITLE
Integrate django-ckeditor

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#19]
We'd like to be able to offer rich-text editing for some fields in Django forms. [Django-CKEditor](https://github.com/django-ckeditor/django-ckeditor) seems to have good repository activity, good documentation, and an intuitive editor interface.

We would use this for the longer community descriptions. (We don't want to allow links in the short description because we're trying to prevent applicants who aren't eligible from contacting mentors.) We could also use this in the application longer forms as well.

**Comment by jameysharp** [comment]
Sage did this in commit 16584445d3c5d26865971c5b703747c2c302e621.
