### ISSUE TITLE
Password reset and multiple accounts issues

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#206]
If we can't find the username, search by email address.

**Comment by sagesharp** [comment]
At first, I thought it was an issue that the password reset form doesn't accept an email address. However, what actually happens is:

- the comrade can't remember their username
- they use the reset password, which accepts their email address
- the reset password email doesn't include their usename
- they go to the reset password page, which doesn't display their username
- they still have no idea what their username is

Therefore:
- they create a second account, using the same email address

Now that means:
- password reset finds two accounts for one email
- it sends a reset request to both emails, but doesn't say what the username is in either email

**Comment by sagesharp** [comment]
Suggested plan of action:
- [ ] Password reset email should include username
- [ ] Ensure that email addresses are unique for newly created accounts
- [ ] Don't allow users to create a a username with another person's email address
- [ ] Check whether any current usernames equals someone else's email address
- [ ] Purge duplicate accounts
- [ ] Login page should accept either username or email address

**Comment by sagesharp** [comment]
Email to send folks that have multiple accounts.

Subject: Outreachy website - multiple accounts resolved

Hi {{ comrade.public_name }},

Outreachy organizers have been reviewing the accounts on the Outreachy website, and we've found multiple accounts with the same email address. In order to add a login page that accepts either a username or an email address, we need to make sure each email address only has one Outreachy website account associated with it.

We detected you had {{ NUM_ACCOUNTS }} accounts on the Outreachy website with the email address {{ EMAIL }}:
- {{ USERNAME1 }}
- {{ USERNAME2 }}

In determining which account to keep, we looked at whether an account had been associated with recording a contribution, mentoring a project, or coordinating a community. If an account with duplicate emails had never participated in a round by filling out an eligibility check, mentoring, or coordinating, we deleted the account. You can always create a new account on the Outreachy website to participate in a new round.

We have determined we will keep the following account:
- {{ USERNAME_KEPT }}

Thank you for participating in Outreachy. We hope this change will make it easier for you to participate in the next round.

Outreachy Organizers
{{ organizer footer }}

**Comment by jameysharp** [comment]
The rules @sagesharp and I just decided on are as follows.

If there are duplicate accounts for the same email address, **delete** those accounts that have no objects which the delete would cascade to.

If there are still duplicates, **delete** those accounts where a Comrade object is the only thing a delete would cascade to.

If there are still duplicates, **keep** those accounts where a delete would cascade to any of these models:

- Contribution (which protects FinalApplication, InternSelection, etc)
- MentorApproval
- CoordinatorApproval

If at least one account is kept by that rule, then **delete** all other accounts for the same email address.

If there are still duplicates left, leave them for manual review or future work.

Note that the first two steps of this procedure can delete _all_ accounts for an email address, but we've decided there's no useful information in those accounts.

**Comment by jameysharp** [comment]
I've pushed the following:

- Fixes to the password-reset email template to inform recipients of which username each reset link is for. People who forgot their username probably found this incredibly unhelpful, and people who had already created multiple accounts with the same email address would have had no way of knowing which link would reset the account they wanted. In either case it seems understandable that people would just create a new account instead, which of course makes the problem worse next time they need a password reset.

- A `./manage.py finddupemail` command, which identifies email addresses that have multiple user accounts attached, and in many cases automatically identifies which account should be kept. When given the `--force` option, the script also deletes the duplicate accounts and send email informing people of which account they can still use.

- A custom registration form that refuses to create a new account if the email address already exists on some other account.

I'm deferring to later the pieces that would support people logging in using either their username or their email address. We have not yet eliminated _all_ duplicate email addresses, and several more hard problems await on that path. Also, I expect the above fixes to address most of the usability problems in practice. But we can revisit this if people continue running into trouble.

**Comment by sagesharp** [comment]
Deployed and run, thanks @jameysharp for all your help!
