### ISSUE TITLE
Switch from requirements.txt to pipenv

### ISSUE THREAD

**Issue by jameysharp** [sagesharp/outreachy-django-wagtail#211]
For many years, the standard way to list dependencies in a Python project has been to include a file conventionally named `requirements.txt`, listing Python packages that can be installed with `pip install -r requirements.txt`. That approach has a number of issues, though.

One issue is that, if you want to pin all your dependencies to known-good versions, then all your transitive dependencies need to be listed as well, which makes it hard to tell whether you still need all the same packages once you stop using one of them. This is the usage mode assumed by `pip freeze`, so the existing tooling has really encouraged this problem.

Another challenge is keeping separate requirements for dev vs production. Some projects provide a separate `requirements-dev.txt`, but again, `pip freeze` doesn't know which packages should go in which file, so the tooling makes this difficult.

[Pipenv](https://docs.pipenv.org/) is a relatively new tool that combines pip with virtualenv in a unified way, and solves both of the above issues as well. Direct dependencies are tracked in a new file named `Pipfile`, which can specify general version constraints or declare that all versions of a dependency should work. The equivalent of `pip freeze` gets stored in a separate file, `Pipfile.lock`, that is automatically managed by Pipenv. That way, removing a direct dependency from `Pipfile` allows automatically removing everything else that's no longer needed from `Pipfile.lock`. And the `Pipfile` has separate sections for production and development requirements, as well as allowing you to specify which version(s) of Python your project supports.

Conveniently, the Heroku Python buildpack already supports detecting the presence of a `Pipfile` and using `pipenv` instead of `requirements.txt`, so making this switch doesn't require any changes to how the site gets deployed to Dokku. It only requires some changes to this project's documentation for the process of setting up a development environment.

Pipenv has documentation on [how to switch from an existing `requirements.txt` to a `Pipfile`](https://docs.pipenv.org/basics/#importing-from-requirements-txt). That will leave a messy `Pipfile` that still has the same problems that the original `requirements.txt` had, but from there it's easier to clean it up, or at least to use better practices when adding new dependencies. So I'd suggest to start there:

- `git add` both the `Pipfile` and `Pipfile.lock` that you get from that import process,
- `git rm` the old `requirements.txt`,
- update the documentation to cover using Pipenv instead of `pip install`,
- and put off the rest of the cleanup for later.

I think this will also eliminate the need for #121.

**Comment by shailysangwan** [comment]
Hi! There's an incompatibility in the dependencies specified in `requirements.txt`.

It pins Willow to version 1.1 and wagtail to version 1.13.1.
But wagtail 1.13.1 has the following [dependency](https://github.com/wagtail/wagtail/blob/stable/1.13.x/setup.py#L33): `"Willow>=1.0,<1.1"`

According to the Willow [changelog](https://willow.readthedocs.io/en/latest/changelog.html#id1), the following features were added in 1.1 over 1.0:

> - Added set_background_color_rgb operation
> - Update MANIFEST.in (Sanny Kumar)

So, should we go with Willow 1.0, which is the only supported version for wagtail 1.13.1?
I see that newer versions of wagtail (2.2x) use Willow 1.1.

**Comment by jameysharp** [comment]
That's an excellent question and I've been wondering about that myself! The error message didn't seem to be hurting things so I was just ignoring it.

You've already answered all the follow-up questions I could possibly ask, which makes this really easy: Since the changelog has so little in it, it seems like it should be safe to drop back to Willow 1.0 until we're ready to upgrade wagtail and everything else.

@sagesharp hasn't wanted to do big upgrades right as the next round starts, which makes sense to me. So we should change as little as possible in the dependencies right now. But I think this change is absolutely worth doing.

I'm excited to see that you're working on this issue, by the way! pipenv is so much nicer than the old tools and I'm looking forward to using it in this project.

**Comment by shailysangwan** [comment]
Great!
I also noticed recently that IDEs like VS Code and PyCharm have started to natively support `pipenv`! :smile: 
Sorry about the repetitive notifications, I just squashed and rebased the commits before making the PR.
