### ISSUE TITLE
Mentors should submit feedback through Outreachy website

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#227]
It's too hard to keep track of whether a mentor has given feedback for their intern. Having that be a part of the organizer dashboard is highly useful. Mentors have also complained about receiving too many feedback emails on the mentors list. Some mentors and organizers like to read the feedback, but we can send it in an aggregate form.

Need to have a way for mentors to give initial, midpoint, and final feedback.

Optionally (not gating this work) - send aggregate comment summaries to the mentors mailing list. (or send a link so people can view all public feedback for interns? then we don't have to send it multiple times as feedback trickles in).

Related to #185

**Comment by sagesharp** [comment]
Initial feedback form for mentors:
 * (Yes/No) Has your intern been in contact to discuss how to approach their first tasks?
 * (Yes/No) Has your intern been asking questions about their first tasks?
 * (Yes/No) Has your intern been active on public project channels, such as the community's chat, forums, issue tracker, mailing list, etc?
 * (Yes/No) Have you provided documentation or other resources to help onboard your intern?
 * (Not scheduled yet / Once a day / Multiple times a week / Once a week / Every other week) How often do you have a real-time chat, video conference, or phone conversation to check in with your intern's progress on tasks?
 * (Date field) What was the last date you were in contact with your intern?
 * (1 hour / 3 hours / 6 hours / 12 hours / 1 day / 2-3 days / 4-5 days / 6-7 days) On average, how long does it take for your intern to respond to your questions or feedback?
 * (1 hour / 3 hours / 6 hours / 12 hours / 1 day / 2-3 days / 4-5 days / 6-7 days) On average, how long does it take for you to respond to your intern's questions or requests for feedback?
 * (long description) Please provide a paragraph describing your intern's progress on establishing communication with you, and ramping up on their first tasks.
 * (Yes/No) Do you believe your Outreachy intern is putting in a full-time, 40 hours a week effort into the internship?
 * (Yes/No) Should your Outreachy intern be paid the initial $1,000 payment? Please base your answer on whether your intern has established communication with their mentors and has start learning how to tackle their first tasks.
 * (Yes/No) Do you want to extend the internship to allow your intern to put in a full-time effort? If you don't believe your intern has put in a full-time effort and should be paid, you may extend the internship.
 * (DateField) If you want to extend the internship, please pick a date when you will be asked to update your intern's initial feedback and authorize payment. Internships can be extended for up to five weeks. We don't recommend extending an internship for more than 1 week at initial feedback. [Validation - should not be more than five weeks from the initial feedback deadline in the RoundPage]

Initial feedback for interns:
 * (Yes/No) Have you been in contact with your mentor to discuss how to approach your first tasks?
 * (Yes/No) Have you been asking questions about your first tasks?
 * (Yes/No) Have you been active on public project channels, such as the community's chat, forums, issue tracker, mailing list, etc?
 * (Yes/No) Has your mentor provided documentation or other resources to help you learn more about your community and your first tasks?
 * (Not scheduled yet / Once a day / Multiple times a week / Once a week / Every other week) How often do you have a real-time chat, video conference, or phone conversation with your mentor to check in on your progress on your first tasks?
 * (Date field) What was the last date you were in contact with your mentor?
 * (1 hour / 3 hours / 6 hours / 12 hours / 1 day / 2-3 days / 4-5 days / 6-7 days) On average, how long does it take for you to respond to your mentor's questions or feedback?
 * (1 hour / 3 hours / 6 hours / 12 hours / 1 day / 2-3 days / 4-5 days / 6-7 days) On average, how long does it take for your mentor to respond to your questions or requests for feedback?
 * (Yes/No) Do you believe your Outreachy mentor is putting in at least 5 hours a week into mentoring you during your internship?
 * (long description) Please provide a paragraph describing how your mentor has (or has not) been helping you. This information will only be seen by Outreachy mentors. We want you to be honest with us if you are having trouble with your mentor, so we can help you get a better internship experience.
 * (10 hours / 20 hours / 30 hours / 40 hours / 50 hours / 60 hours) What is the average number of hours per week you spend on your Outreachy internship? Include time you spend researching questions, communicating with your mentor and the community, reading about the project and the community, working on skills you need in order to complete your tasks, and working on the tasks themselves. Please be honest about the number of hours you are putting in.
 * (long description) Please provide a paragraph describing your progress on establishing communication with your mentor, and ramping up on your first tasks. This information will only be seen by Outreachy mentors. If you are having any difficulties or facing any barriers, please let us know, so we can help you.

The InternSelection needs to have three new fields, which have defaults set from the RoundPage dates:
 * initial feedback deadline
 * midpoint feedback deadline
 * final feedback deadline

Notifications by email:
 * 4 days before feedback is due, mentor(s) and intern receive separate emails asking for them to complete the feedback
 * 1 day before the feedback is due, if there are any interns who have not received feedback from one of the mentor(s), email all their mentors and their coordinator(s)

We only want to receive feedback from one mentor. That should be made clear in the notification emails (it's okay to write the email as a stub for now, and I will edit it later). The form should "close" after we've received feedback and reopen before the extended feedback deadline.

Don't send feedback requests to interns who are not in good standing. Make it clear the notification email is an automated email (in case mentors are already talking with us).

The Outreachy dashboard should show:
 * a list of interns that have not received feedback for a milestone (including their email address, mentor(s) email addresses, and coordinators email address to ping them would be good) and the date when that feedback was due
 * a list of interns with extensions, when all their feedback miles are due, and a button to send a manual reminder for updated feedback
 * a link for the feedback export page

The feedback export page should:
 * include a link to download a zip file for all mentor and intern feedback
 * include a text box with a copy-paste email we can send to Conservancy

Sample email to Conservancy:

```
[sfconservancy.org #TICKETNUMBER] [Outreachy Month Year] Final payment authorization

Hi SFC accounting team,

We've received successful final feedback for X of Y interns.

One intern (NAME) decided not to participate in the program,
and never received the initial stipend.

One intern (NAME) did not put in a full-time effort. They
failed the mid-point evaluation, and were not paid the mid-point
stipend. You should already have received a file with discussion with
their mentor.

NUMBER interns have an extension:

 - NAME          # community
   (final feedback due DATE)
 - NAME            # community
   (final feedback due DATE)

The status of one additional intern (NAME) is under discussion.

Mentors have not given feedback for interns NAME, NAME, and NAME.

The feedback is attached in a zip file containing JSON files of the
mentor's feedback form answers.

Sage Sharp
Outreachy Organizer

-----

NAME OF SUCCESSFUL INTERN     # community
NAME OF SUCCESSFUL INTERN     # community

```

**Comment by jameysharp** [comment]
Some thoughts from reviewing the text of the questions...

In the mentor questions, I think this sentence is confusing:

> If you don't believe your intern has put in a full-time effort and should be paid, you may extend the internship.

In the intern questions, I think this was supposed to say "Outreachy organizers":

> This information will only be seen by Outreachy mentors.

In general I think the template around both forms should explain who is allowed to view the answers, and why the information is being collected.

**Comment by sagesharp** [comment]
> If you don't believe your intern has put in a full-time effort and should be paid, you may extend the internship.

Sometimes interns do not put in a full-time effort. In this case, one of the options is to delay payment of their stipend and extend their internship a specific number of weeks. You will be asked to re-evaluate your intern after the extension is done.

Agreed that we'll need to explain who can view the info. We should also add this to our GDPR documentation, but note that we cannot remove mentor feedback because it is required by our fiscal sponsor as a record of the reason for financial decisions.

**Comment by jameysharp** [comment]
Since this seems to have worked pretty well for initial feedback, I think it's time to close this issue. Midterm and final feedback still need to be implemented but now we have a demonstration of how to do those.
