### ISSUE TITLE
Error showing projects for not logged in and logged in users

### ISSUE THREAD

**Issue by Lereena** [sagesharp/outreachy-django-wagtail#241]
https://www.outreachy.org/apply/project-selection/ shows some information about the projects of the current round, if you are logged off, but if you are logged in and expect approval of an initial application, there is no information about the projects at all, the page ends with the section "Preparing for the Application Process"

**Comment by sagesharp** [comment]
This should have been fixed in commit fd26af69340d6691b37725575cd963d35b0a4b47

Thanks for reporting this, @Lereena!
