### ISSUE TITLE
Add calendar date selector for initial application

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#242]
There are several different time commitment classes that could use fields where applicants can select a date from a calendar. Currently, we request all dates in the form of YYYY-MM-DD. Many applicants get their term dates wrong (typically using the wrong year or month). A calendar popup might help them select the right dates.

**Comment by sagesharp** [comment]
Examples of pages that need date selectors:
- /eligibility/
- say that you're a student, and enter dates about your school terms.

**Comment by jameysharp** [comment]
I think we fixed this in 154a46badd42b08fe6043ea0befa85211f0d9774
