### ISSUE TITLE
Add caste to CoC and essay questions

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#264]
In India, the caste system is often used to discriminate against people. Consider adding it to the Code of Conduct and to the essay question about background similarities.

**Comment by sagesharp** [comment]
In the Outreachy initial application process, we ask applicants several essay questions. One of those questions is whether they see people who share the same identity and background in their education system. That essay question has a list of protected classes, which is included in our Code of Conduct, as a starting point to get people to understand what kind of 'identity' we're talking about. The essay question and the Code of Conduct should be modified to include caste as a protected class.

Edit the protected classes in the ['Our Pledge' section of the Code of Conduct mark down file](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/CODE-OF-CONDUCT.md#our-pledge). Add caste after body size (to keep things in alphabetical order).

Next, you'll need to make sure someone filling out the initial application will see caste in the form text. The initial application is comprised of several classes: [ApplicantApproval](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L2209), [WorkEligibility](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L2439), [PaymentEligibility](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L2465), [PriorFOSSExperience](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L2479), [ApplicantGenderIdentity](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L2545), [ApplicantRaceEthnicityInformation](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L2651), [BarriersToParticipation](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L2661), and the various time commitment, school, and promotion tracking models.

The essay questions, including the text that's displayed in the form, can be found in the [BarriersToParticipation](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L2661) class. You'll need to modify the field help text to include caste (after body size). The field help text can be [found in the BarriersToParticipation model](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L2675).

Next, go to the Django admin interface in your local copy of the website. (You'll often hear me call the Django admin interface the 'backend' of the website, even though that isn't the correct term.) You can view the Django admin interface by going to localhost:8000/django-admin. The Django documentation will ask you to go to localhost:8000/admin, but for our project, that's actually the Wagtail admin interface.

Once you're in the Django admin interface, click on the Add button next to the 'Round pages' link. Create a RoundPage where the application period is currently open by modifying the dates for this round. You'll need to make sure that the RoundPage appsopen date is some time before today, and the appsclose and appslate dates are sometime after today. That will ensure the application period is open.

Once the round is open, you can test the initial application process and see whether the field text you modified is changed. Go to localhost:8000/eligibility/, create a new account (you'll see the account verification link appear in the runserver log, which you'll need to follow), and fill out the form.

If you fill out the form in a way that makes you ineligible for this round, you'll still be asked the essay questions.

Jamey made some previous tests for the initial application, so he'll describe how you can add a test to ensure your code is correct.

**Comment by jameysharp** [comment]
I wouldn't suggest using either the Django or Wagtail admin interfaces to create a RoundPage. Instead, do the following (which we should document).

Run `./manage.py shell`. Then in that Python shell, run:

```python
from home.factories import *
models.RoundPage.objects.all().delete() # optional: removes any rounds you already had
RoundPageFactory(start_from='lateorgs')
```

Now in your database you have a RoundPage that is currently in the middle of its application period.

**Comment by sagesharp** [comment]
This issue is also fixed in the initial-application-changes branch.
