### ISSUE TITLE
Ask for job description in initial application

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#272]
When we ask applicants how many hours per week they're working in a part-time job, we don't currently ask them for a description of the job. It's very different to have a part-time 20 hours a week job as a library assistant vs a half-time technical internship. The Outreachy organizers agree that if an applicant has a part-time job involving technical work, they are unlikely to succeed doing 60 hours of technical work a week. Even if they are successful, we don't want to encourage interns to burn themselves out.

Make a new mandatory [character field](https://docs.djangoproject.com/en/1.11/ref/models/fields/#charfield) for the job description in the [EmploymentTimeCommitment model](https://github.com/sagesharp/outreachy-django-wagtail/blob/037637a0621a8bcef810831ed6f8e2dbb1b17dcc/home/models.py#L2699). You'll need to [look at the documentation](https://docs.djangoproject.com/en/1.11/topics/db/models/#field-options) for how to require a person to fill out the field. Then [create a new migration](https://docs.djangoproject.com/en/1.11/topics/migrations/) to modify the database schema to include the new field.

Once you add the new field, it's time to make sure the initial application form [view](https://docs.djangoproject.com/en/1.11/intro/tutorial03/) displays the field. Otherwise the field will not be shown to the applicant. The [view class](https://github.com/sagesharp/outreachy-django-wagtail/blob/037637a0621a8bcef810831ed6f8e2dbb1b17dcc/home/views.py#L385) for the whole initial application is a [form wizard](https://django-formtools.readthedocs.io/en/latest/). A form wizard is a Django package (add-on) that creates a series of forms in separate views. You'll need to modify the field list in the information for the [employment questions view](https://github.com/sagesharp/outreachy-django-wagtail/blob/037637a0621a8bcef810831ed6f8e2dbb1b17dcc/home/views.py#L631) to include the name of the new field.

Then, in your local deployment, test that the new field is shown and that you can enter a job description. You'll need to answer 'yes' to the question 'Will you be an employee (for any number of hours) during the Outreachy internship period?' on the time commitments summary view in order to be asked details about the employment.

Set a warning flag in the Outreachy application review if the applicant has a part-time job that's 10 or more hours a week.

**Comment by soph213** [comment]
I'd like to have a go at this, if that's okay? I'm relatively new to Python but like a good challenge!
