### ISSUE TITLE
Setup error and preferred communication channel

### ISSUE THREAD

**Issue by Gouravchawla** [sagesharp/outreachy-django-wagtail#279]
Hi,

I was trying to setup the project and I faced the below mentioned error. Also, it would be helpful to know the **preferred communication channel**.

Here is what I was trying to do:

`
To do this navigate to http://127.0.0.1:8000/django-admin/home/roundpage/add/
`

Here is the error screenshot with my OS specs:
Fedora 27 (x64)
Python 3.6.6
Firefox browser

![image](https://user-images.githubusercontent.com/2922351/52039004-529f4f00-2559-11e9-986b-4fc994e71e28.png)

**Comment by sagesharp** [comment]
Hi @Gouravchawla! Setting up the round page requires using the Wagtail interface, rather than the Django admin interface. We've updated the documentation to tell developers how to do that. Thanks for reporting this issue!
