### ISSUE TITLE
Say Community and Project applicant views are "previews"

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#39]
"Preview" is the magic word that means "don't share this page with applicants". Note who can view the preview, and that you should send applicants to the rounds page once the community is approved.

**Comment by jameysharp** [comment]
Also, only reveal information on the preview pages that would also be shown on the corresponding public landing pages, except if the visitor is logged in as an approved mentor or coordinator or organizer.
