### ISSUE TITLE
Send email when Community is approved by Outreachy organizers

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#53]
When a Community is approved by Outreachy Organizers, we need to let coordinators and mentors know what actions to take next.

To: Coordinators
- Subject: NAME approved to participate in Outreachy
- action -> create gmail filter for mentors mailing list RIGHT NOW
- action -> get mentors to add their projects
- action -> approve or reject pending projects (have a list)

For each approved coordinator:
- To: subscribe email address for mentors mailing list
  - Subject: subscribe
  - Body: subscribe "Name" <email>

To: approved mentors with approved projects
- Subject: NAME approved to participate in Outreachy
- action -> create gmail filter for mentors mailing list RIGHT NOW
- (?) action -> if approved projects with mentors, link to community landing page, they can start advertising their community

For each approved mentor with an approved project:
- To: subscribe email address for mentors mailing list
  - Subject: subscribe
  - Body: subscribe "Name" <email>

**Comment by jameysharp** [comment]
As far as I can tell, this is done.
