### ISSUE TITLE
Subscribe mentors and coordinators to announce list

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#79]
Mentors and coordinators should be subscribed to both our public announcement mailing list and the private mentors mailing list. So we need to send two emails.

**Comment by jameysharp** [comment]
Take a look at <https://www.outreachy.org/dashboard/trusted-volunteers/> which has a textarea you should be able to copy all the email addresses from and paste into Mailman's mass-subscribe form. I can't actually check that it's working right on the live site because it's staff-only, naturally... 😅

**Comment by sagesharp** [comment]
I can't test this until we approve communities, and that's gated on getting the eligibility checking in place.
