### ISSUE TITLE
Only seeing own account on CoordinatorApproval objects in dashboard

### ISSUE THREAD

**Issue by madprime** [sagesharp/outreachy-django-wagtail#81]
First reported by @gedankenstuecke – for me as well, it seems like only my own account is listed in CoordinatorApproval objects on the dashboard.

Might be here, maybe only returning the user themselves:
https://github.com/sagesharp/outreachy-django-wagtail/blob/f7ccbdece36395b62d315469be9658d560154cb9/home/models.py#L930

![image](https://user-images.githubusercontent.com/82631/35026326-45ee2180-faff-11e7-8999-c48de6f73174.png)

**Comment by jameysharp** [comment]
I'm too sleepy to reason this through right now, but I think you have correctly identified the problem, and I definitely agree that @gedankenstuecke's pull request is going in the right direction.

My gut feeling is that the pull request still isn't quite right, so I want to reconsider it after some sleep. But thank you both so much for the rapid testing, debugging, and proposed fixes!

**Comment by gedankenstuecke** [comment]
Thanks already for looking into this @jameysharp! 

I'm not 100% confident that my solution is the *right* fix either, largely as I'm not a 100% sure whether my hack of creating the `RoundPage` (c.f. #83) was the right approach. 

In my two-user setup #82 leads to a) correctly showing the pending request to the comrade who's already a coordinator of a community and b) after `comrade A` approves of `comrade B`, the latter will see both themselves plus `comrade A` on the dashboard as approved. At least that part seems to work fine. Plus if `super-comrade C` looks at their dashboard all things show up as expected.

I appreciate more thorough testing from your side and all the time/energy you're all putting into this. 😄 👍
