### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by JuliaLawall** [sagesharp/outreachy-django-wagtail#85]
After filling in the information to add the Linux kernel as a community, I was sent to the URL https://www.outreachy.org/communities/cfp/add/, which showed the message:

Internal server error
Sorry, there seems to be an error. Please try again soon.

Is this a known problem, or do I have to try again, eg with another browser?

**Comment by jameysharp** [comment]
Hi Julia! Sage and I will look into what happened, but we suspect the error occurred because Sage already added the "Linux Kernel" community, and you just need to click the "Coordinate for This Community" button at https://www.outreachy.org/communities/cfp/linux-kernel/.

**Comment by JuliaLawall** [comment]
On Tue, 23 Jan 2018, Jamey Sharp wrote:

>
> Hi Julia! Sage and I will look into what happened, but we suspect the error
> occurred because Sage already added the "Linux Kernel" community, and you
> just need to click the "Coordinate for This Community" button at
> https://www.outreachy.org/communities/cfp/linux-kernel/.

Ah, OK, thanks!  I've done that, and it seems to have worked.

julia

**Comment by jameysharp** [comment]
Oh, good!

I found the log entries corresponding to those internal server error messages you saw, and our guess was right: submitting another community with the same name violated a database-level uniqueness constraint, and we didn't write the code we should have to check for that case. I've filed that as issue #86 to remind us to come back to it.

We both feel bad that you had so much trouble... Sorry! 😓

Perhaps you can help us with one more thing? On the CFP page where you found the "Submit a New Community" button, we have this text right above it which we hoped would have saved you this trouble:

> First, double check that the community isn't listed in the participating communities or past communities list. If the community is listed as a past Outreachy community, you can sign up to coordinate for that community. Coordinators will need to review the coordinator duties and community requirements for participating in internships. Then submit a new community for review.

Clearly we didn't do a good enough job of indicating what steps to take. I could guess that the above paragraph is confusing, or that it's too easy to skip over it when there's a nice big green button to click below it, but direct feedback from you would be better than any guess. Can you tell us what you noticed, what was confusing, and how you ended up clicking the new community button instead of finding your community listed later?

Your feedback will help us make this process less confusing for other community coordinators. Thanks!

**Comment by JuliaLawall** [comment]
On Tue, 23 Jan 2018, Jamey Sharp wrote:

>
> Oh, good!
>
> I found the log entries corresponding to those internal server error messages you saw, and our guess was right: submitting another community with the same name violated a database-level uniqueness constraint, and we didn't write the code we should
> have to check for that case. I've filed that as issue #86 to remind us to come back to it.
>
> We both feel bad that you had so much trouble... Sorry! 😓
>
> Perhaps you can help us with one more thing? On the CFP page where you found the "Submit a New Community" button, we have this text right above it which we hoped would have saved you this trouble:
>
>       First, double check that the community isn't listed in the participating communities or past communities list. If the community is listed as a past Outreachy community, you can sign up to coordinate for that community. Coordinators will
>       need to review the coordinator duties and community requirements for participating in internships. Then submit a new community for review.
>
> Clearly we didn't do a good enough job of indicating what steps to take. I could guess that the above paragraph is confusing, or that it's too easy to skip over it when there's a nice big green button to click below it, but direct feedback from you
> would be better than any guess. Can you tell us what you noticed, what was confusing, and how you ended up clicking the new community button instead of finding your community listed later?
>
> Your feedback will help us make this process less confusing for other community coordinators. Thanks!

I definitely remember seeing the paragraph, but I think I didn't
completely understand the implications.  I sort of assumed that since the
system was new, all communities would be new too.

Maybe it would help a little to say "If the community is listed as a past
Outreachy community, then the community already exists, and all you have
to do is sign up to coordinate for that community."

Another thing I noticed was that when I filled in the new community form,
there were entries for things like the code of conduct, but when I did
things properly and clicked on the link to add extra information, I only
found the option to fill in the organization's URL, but none of the more
detailed information.  Did Sage add it already?

thanks,
julia

**Comment by jameysharp** [comment]
Thanks for your feedback! That's very helpful.

Sage decided to only ask for details like code of conduct from communities who are participating for the first time. Returning communities have already been evaluated for whether they're appropriate for Outreachy and don't need to go through all those details again.

**Comment by JuliaLawall** [comment]
On Tue, 23 Jan 2018, Jamey Sharp wrote:

>
> Thanks for your feedback! That's very helpful.
>
> Sage decided to only ask for details like code of conduct from communities
> who are participating for the first time. Returning communities have already
> been evaluated for whether they're appropriate for Outreachy and don't need
> to go through all those details again.

OK, thanks for the clarification.

Good luck in getting the whole application system in place (I saw some
panicked tweets from Sage a few weeks ago...).

julia
